### ISSUE TITLE
Cannot connect to world peergroup in junit tests

### ISSUE THREAD

**Issue by condast** [chaupal/jxse#3]
Should be fixed in the most recent update

**Comment by condast** [comment]
Hi Kees,
Downloaded https://github.com/chaupal/jxse, removed all netty references.
It builds, but a bunch of tests fail:
Failed tests:
  DocumentTest.testDOMXMLStructuredDoc:475->_testAttributesSolo:411 Caught
an unexpected exception - junit.framework.AssertionFailedError: should be 1
attribute

Tests in error:
  RelayedHttp2CommsTest.initPeers:27 » PeerGroup Could not locate World
PeerGrou...
  BlockingPipeAcceptTest.initPeers:39 » PeerGroup Could not locate World
PeerGro...
  AdHocHttp2CommsTest.createPeers:31 » PeerGroup Could not locate World
PeerGrou...
  AdHocTcpCommsTest.createPeers:31 » PeerGroup Could not locate World
PeerGroup ...
  RelayedTcpCommsTest.initPeers:27 » PeerGroup Could not locate World
PeerGroup ...
  AdHocHttpCommsTest.createPeers:31 » PeerGroup Could not locate World
PeerGroup...
  RelayedHttpCommsTest.initPeers:27 » PeerGroup Could not locate World
PeerGroup...
  TestSuite.net.jxta.impl.loader.RefJxtaLoaderTest » PeerGroup Could not
locate ...
  TestSuite.net.jxta.impl.loader.RefJxtaLoaderTest » NullPointer
  TestRouteAdv.configureAlice:119 » PeerGroup Could not locate World
PeerGroup M...
  TestRouteAdv.configureAlice:119 » PeerGroup Could not locate World
PeerGroup M...
  TestRouteAdv.configureAlice:119 » PeerGroup Could not locate World
PeerGroup M...
  TestRouteAdv.configureAlice:119 » PeerGroup Could not locate World
PeerGroup M...
  TestRouteAdv.configureAlice:119 » PeerGroup Could not locate World
PeerGroup M...
  TestRouteAdv.configureAlice:119 » PeerGroup Could not locate World
PeerGroup M...

Most at
net.jxta.peergroup.WorldPeerGroupFactory.getDefaultWorldPeerGroupClass(WorldPeerGroupFactory.java:244)
e.g.
Running net.jxse.systemtests.colocated.pipes.BlockingPipeAcceptTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.4 sec <<<
FAILURE! - in net.jxse.systemtests.colocated.pipes.BlockingPipeAcceptTest
testBlockingAccept(net.jxse.systemtests.colocated.pipes.BlockingPipeAcceptTest)
 Time elapsed: 0.367 sec  <<< ERROR!
net.jxta.exception.PeerGroupException: Could not locate World PeerGroup
Module Implementation.
at
net.jxta.peergroup.WorldPeerGroupFactory.getDefaultWorldPeerGroupClass(WorldPeerGroupFactory.java:244)
at
net.jxta.peergroup.WorldPeerGroupFactory.<init>(WorldPeerGroupFactory.java:184)
at
net.jxta.peergroup.NetPeerGroupFactory.<init>(NetPeerGroupFactory.java:203)
at net.jxta.platform.NetworkManager.startNetwork(NetworkManager.java:408)
at
net.jxse.systemtests.colocated.pipes.BlockingPipeAcceptTest.initPeers(BlockingPipeAcceptTest.java:39)

Also:
net.jxta.impl.loader.RefJxtaLoaderTest(junit.framework.TestSuite)  Time
elapsed: 0.347 sec  <<< ERROR!
java.lang.NullPointerException: null
at
net.jxta.impl.loader.RefJxtaLoaderTest.tearDownClass(RefJxtaLoaderTest.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
at
org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
at
org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
at
org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
at
org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
at
org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
at
org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
at
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Have I missed something?

Thank you
Alex Bootman

**Comment by condast** [comment]
This problem has been fixed. apparently the CompaitibilityUtils version check does not work well with JAVA 15, and therefore the version check failed.
